### PR TITLE
add high-score tables

### PR DESCRIPTION
**Pull request by ericLemanissier**
This gives the list of the files with the most todos, the most LOC, and the most todos per LOC
cf https://ericlemanissier.github.io/serenity-fixmes/flamegraph

### CODE REVIEW

**Comment by BenWiederhake** [comment]
Happy new year! It took a while until I got around to this PR.

Looks awesome! But why is there a text field to "filter" stuff when it only filters by text? Is there a way to simply remove filtering?
I mean, it does look a bit goofy, doesn't it:
Bildschirmfoto_2023-01-01_17-28-08

Also, yet another external dependency, so I ask again: Can this be vendored? ^^

**Comment by ericLemanissier** [comment]
Happy new year to you too !
Indeed the only column where "filter" makes sense here is the last one. I just removed all the footers, and we can still filter/search by using the search textbox on the top right corner of the table.
I also just vendored jquery and datatables.

**Comment by BenWiederhake** [comment]
Merged, thanks! (Github is confused because I squashed it.)

In case you'd like feedback:
- There's really no need to have many commits revising the same few lines of code. In these particular cases it's probably best to cut to the chase and only make a PR with the final version of the ten lines of new code, because reading the history doesn't provide much understanding. That's why I squashed this PR into a single commit.
- Please pay a bit more attention to naming.
    * The PR and commit subject sound like you're adding user-based high-score tables. That's why I changed them.
    * The functions "get_node" and "set_value" do way way more than their name would imply, so the name isn't just unhelpful but even misleading. I'll change them when I get around to it.
    * The filename "todo.csv" sounds like it's going to contain mostly the same stuff as "todo.json", so the name is misleading. That's why I changed it.
- The tab seems to consume a boatload of memory and CPU now, even after the graphs have fully loaded. Just switching tabs forth and back has a considerable lag to it. I have no idea how to fix that, but if you get around to it, fixing this would be nice.
- The numbers are off by about 200. I was lazy and ignored that in #2 you re-implemented searching and counting of fixmes, and used different criteria than the "main" history thing. Why? The biggest differences I can see are:
    * `generate_flame_graph()` includes all files that are not in the git repo, e.g. Ports, generated files, Toolchain. Scanning these files isn't particularly expensive, but it's a lot of files, and they're by definition all false positives since they can't be fixed.
    * `generate_flame_graph()` excludes many file types that contain FIXMEs. Here's a table of how many FIXMEs this approach misses by file type:
          1 *.ipc
          1 *.ipp
          2 *.css
          2 *.in
          3 *.bin
          3 *.json
          3 *.ld
          4 .clang-tidy
          4 *.py
         11 *.S
         23 *.md
         25 *.yml
         69 *.patch
        101 *.idl
    The solution is NOT to add all of these extensions to the hard-coded list, but rather to use the same approach as in `count_fixmes()`. `grep` is very often faster than trying to implement your own text search, *even* if just searching for fixed strings.
- Note to self: generate_flame_graph doesn't checkout the latest commit, so in some weird corner cases it might produce the wrong results for a few minutes (until the next commit arrives).

**Comment by ericLemanissier** [comment]
> Merged, thanks! (Github is confused because I squashed it.)

thank you.
> 
> In case you'd like feedback:

I live for feedback !
> 
> * There's really no need to have many commits revising the same few lines of code. In these particular cases it's probably best to cut to the chase and only make a PR with the final version of the ten lines of new code, because reading the history doesn't provide much understanding. That's why I squashed this PR into a single commit.

I usually keep history in pull requests, because most of the projects I contribute to use [github's "squash and merge" button](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request#merging-a-pull-request), which allows iterative reviews. Next time I'll keep a single commit.
> * Please pay a bit more attention to naming.
>   
>   * The PR and commit subject sound like you're adding user-based high-score tables. That's why I changed them.
>   * The functions "get_node" and "set_value" do way way more than their name would imply, so the name isn't just unhelpful but even misleading. I'll change them when I get around to it.
>   * The filename "todo.csv" sounds like it's going to contain mostly the same stuff as "todo.json", so the name is misleading. That's why I changed it.

Please do not hesitate to keep asking for corrections (including naming, and pull request title etc..) until you can simply merge as-is.
> * The tab seems to consume a boatload of memory and CPU now, even after the graphs have fully loaded. Just switching tabs forth and back has a considerable lag to it. I have no idea how to fix that, but if you get around to it, fixing this would be nice.

I tried with chrome and edge. I'll do a test on firefox and try to improve the situation.
> * The numbers are off by about 200. I was lazy and ignored that in [add a flame graph #2](https://github.com/BenWiederhake/serenity-fixmes/pull/2) you re-implemented searching and counting of fixmes, and used different criteria than the "main" history thing. Why? The biggest differences I can see are:
>   
>   * `generate_flame_graph()` includes all files that are not in the git repo, e.g. Ports, generated files, Toolchain. Scanning these files isn't particularly expensive, but it's a lot of files, and they're by definition all false positives since they can't be fixed.

Indeed. It's not a problem on the github actions I set up in https://github.com/ericLemanissier/serenity-fixmes/blob/master/.github/workflows/main.yml because it always uses a fresh clone, but I did not know you were using a persistent clone, used also for building serenity.
>   * `generate_flame_graph()` excludes many file types that contain FIXMEs. Here's a table of how many FIXMEs this approach misses by file type:
>     1 *.ipc
>     1 *.ipp
>     2 *.css
>     2 *.in
>     3 *.bin
>     3 *.json
>     3 *.ld
>     4 .clang-tidy
>     4 *.py
>     11 *.S
>     23 *.md
>     25 *.yml
>     69 *.patch
>     101 *.idl
>     The solution is NOT to add all of these extensions to the hard-coded list, but rather to use the same approach as in `count_fixmes()`. `grep` is very often faster than trying to implement your own text search, _even_ if just searching for fixed strings.

I used pyhon to count todos, because I wanted to count LOC too. If you are ok with the idea I can replace this python counting by calls to grep and cloc/gocloc. the drawback is that it introduces a new system dependency. We could use `wc -l` but that'll count comments (note that my manual python wrongfully counts c++'s `/* ... */` comments as LOC)
> * Note to self: generate_flame_graph doesn't checkout the latest commit, so in some weird corner cases it might produce the wrong results for a few minutes (until the next commit arrives).

I don't think LOC can be counted without checking out the corresponding commit

**Comment by BenWiederhake** [comment]
> I usually keep history in pull requests, because most of the projects I contribute to use [github's "squash and merge" button](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request#merging-a-pull-request), which allows iterative reviews. Next time I'll keep a single commit.

Ah! That's exactly what I did, just manually. ^^

> Please do not hesitate to keep asking for corrections (including naming, and pull request title etc..) until you can simply merge as-is.

Will do!

> > * The tab seems to consume a boatload of memory and CPU now, even after the graphs have fully loaded. Just switching tabs forth and back has a considerable lag to it. I have no idea how to fix that, but if you get around to it, fixing this would be nice.
> 
> I tried with chrome and edge. I'll do a test on firefox and try to improve the situation.

AFAIK Chrome and Edge are mostly the same browser, just with different frontends for the UI. So that doesn't really say much. You guessed correctly, I use Firefox.

For a half-serious point of reference: Browser loads the graphs-as-images page quickly, my only complaints would be about the downscaling. In contrast, the flamegraphs *do* load, crash with what I guess is an OOM, and then CrashReporter OOMs terribly, spitting out endless error messages to dbg.
Yes, I know, I'm comparing apples (static image of a graph) and oranges (interactively navigable tree), but I think you get the gist: This particular graph is very heavy.
(Fixing that is not important, just annoying.)

> I used pyhon to count todos, because I wanted to count LOC too. If you are ok with the idea I can replace this python counting by calls to grep and cloc/gocloc. the drawback is that it introduces a new system dependency. We could use `wc -l` but that'll count comments (note that my manual python wrongfully counts c++'s `/* ... */` comments as LOC)

Ah, I see the issue.

- grep+gocloc sounds good
- Doing it in python sounds good
… but what's more important is covering all files of the repo. Because you only look for particular filename extensions, it currently misses about 200 FIXMEs. Here's a semi-random sampling for each of the extensions:

```
Userland/DevTools/HackStudio/LanguageServers/LanguageClient.ipc:6:    todo_entries_in_document(DeprecatedString filename, Vector<CodeComprehension::TodoEntry> todo_entries) =|
Userland/Services/WindowServer/ScreenLayout.ipp:357:    // TODO: make this a little more sophisticated in case a more complex layout is already configured
Userland/Libraries/LibWeb/CSS/Default.css:23:/* FIXME: This doesn't seem right. */
Toolchain/CMake/GNUToolchain.txt.in:25:# FIXME: We could eliminate this setting by building LibC and support asm files (crti.o, crtn.o)
Userland/Libraries/LibWeb/CSS/Properties.json:1137:    "__comment": "FIXME: Initial value is really `medium invert none` but we don't yet parse the outline shorthand.",
Kernel/Arch/aarch64/linker.ld:3:/* TODO: Add FLAGS to the program headers */
.clang-tidy:52:    value: 100 # FIXME: Lower this (30? 50?), and refactor complex functions
Meta/generate-libwasm-spec-test.py:313:                # FIXME: This is going to mess up the different kinds of nan
Userland/Libraries/LibELF/Arch/aarch64/plt_trampoline.S:12:    # FIXME: Possibly incomplete.
Documentation/Browser/LibWebFromLoadingToPainting.md:99:- If an individual table component box is found outside the context of a full table, a set of anonymous table boxes are generated to compensate and ensure that there's always a fully-formed table. (FIXME: This is currently buggy..)
Meta/Azure/Lagom.yml:145:          # FIXME: enable detect_stack_use_after_return=1 #7420
Ports/OpenJDK/patches/0004-hotspot-Add-workarounds-for-BSD-differences-from-ser.patch:315:+  return OS_ERR; // FIXME: Get stats from Network interface daemon
Userland/Libraries/LibWeb/HTML/HTMLFormElement.idl:15:    // FIXME: Should be a HTMLFormControlsCollection
```

My point is that these FIXMEs are (mostly) real, and should show up in a flamegraph about fixmes :)

> > * Note to self: generate_flame_graph doesn't checkout the latest commit, so in some weird corner cases it might produce the wrong results for a few minutes (until the next commit arrives).
> 
> I don't think LOC can be counted without checking out the corresponding commit

Checking out the corresponding commit is perfectly fine! I admit, I'm nitpicking here, and could be fixed by a simple `git checkout $NEWEST_COMMIT_HASH`.
(And to nitpick to the max: In *theory*, all of this should be possible without checking anything out to the worktree, using something like libgit2. However, I decided against this route, because then I couldn't use grep and such.)

**Pull request closed without merging**
