### PR TITLE
add a flame graph

### PR DESCRIPTION
**Pull request by ericLemanissier**
This shows the repartition of todos, and LOC, in interractive graphs:
image
https://ericlemanissier.github.io/serenity-fixmes/flamegraph

### CODE REVIEW

**Comment by BenWiederhake** [comment]
I just played around a lot with it, and it looks awesome! :D
I love that one can zoom into each component just by clicking on it.

For some reason it took several attempts before it finally worked, do you know what might be up with that? Also, I see some warnings about Quirks mode, so it's probably a good idea to add a `<!DOCTYPE html>` at the top. Might that be the reason?

EDIT: Hmm, trying this again in a fresh Firefox container doesn't reproduce the issue. Perhaps I was just too impatient?

**Comment by BenWiederhake** [comment]
Gotcha! Apparently sometimes d3js.org doesn't serve the javascript file?

    Loading failed for the <script> with source “https://d3js.org/d3.v7.js”.
    
Can this file be vendored into the repository? That would prevent that error, and marginally increase privacy.

**Comment by ericLemanissier** [comment]
> Can this file be vendored into the repository? That would prevent that error, and marginally increase privacy.

probably yes, we just need to save https://d3js.org/d3.v7.js, with a copy of the license https://github.com/d3/d3/blob/main/LICENSE

**Comment by ericLemanissier** [comment]
some flamegraphs have hover legend and/or captions : http://martinspier.io/d3-flame-graph/. I can add them too if you feel it makes the graph more usable (see https://github.com/spiermar/d3-flame-graph)
You may also want to add the flamegraph on the existing index page instead of a separate one.
One last thing, I'm not entirely sure that the LOC flamegraph is useful

**Comment by BenWiederhake** [comment]
Including the ISC license sounds perfectly fine with me. My hope is that vendoring the library makes loading the webpage more reliable.
(It's a weird situation; on the one hand I see failing http requests to d3js.org, on the other I can't imagine why it should be unreliable, after all it seems to be made for this particular purpose. Hmm. Maybe I misunderstand something. Either way, vendoring it is hopefully not a terrible thing.)

I liked comparing the FIXMEs with the lines of code, just to see what the ratios are. So I'd say keep it in, it's more buttons to press and play around ^^

Btw, radical alternative: We seem to have very different goals here (tracking over time using self-hosted hardware vs. showing the current state of affairs using github actions). I'd be very happy if you make your own webpage, and we link to each other. How does that sound?

**Comment by ericLemanissier** [comment]
> Btw, radical alternative: We seem to have very different goals here (tracking over time using self-hosted hardware vs. showing the current state of affairs using github actions). I'd be very happy if you make your own webpage, and we link to each other. How does that sound?

I'm fine either way. At some point I imagined putting a manual slider, allowing to choose the point in time we are viewing/ animating the flames while sliding. we may see some dancing flames ! But I realistically won't have the time to do it in the coming weeks, so...
Feel free to close the PR if you prefer. In this case I'll make a dedicated page with proper description and usability, and then I'll simply make a PR to include a link on your page.

**Comment by BenWiederhake** [comment]
Scrolling through time would require a heck of a lot of data though ^^'
Each flamegraph JSON is already 400K, imagine that times 44K (the number of commits now), that would be 17 MB already. So, a cleverer approach would be necessary; but it would indeed be very cool!

I like the flamegraph, but wasn't sure how you'd like this to handle, and assumed you'd do the license thing.

Btw, I finally figured out the connectivity issue: Apparently my ISP is currently having trouble with IPv6, and my browser tries to connect via IPv6 first, and apparently takes very long to fail over to IPv4, for some reason. So it's not critical, but I'll change it.

**Comment by BenWiederhake** [comment]
Merged in https://github.com/BenWiederhake/serenity-fixmes/commit/07093c14ba77ccf57d7ed742d48b04018de41d3c , github just doesn't understand it because I tweaked the commit subject.

Thank you, ericLemanissier!

**Comment by BenWiederhake** [comment]
Aaand it's live: https://benwiederhake.github.io/serenity-fixmes/flamegraph.html

**Pull request closed without merging**
